Simplify ERC20
OpenZeppelin/cairo-contracts pull request #121
Opened 2022-01-03 01:48 UTC by andrew-fleming

# Simplify ERC20

## Summary

This PR includes a further abstraction of the extensibility pattern for ERC20 contracts and resolves #109 . This structure follows the concept that all of the necessary contract logic occurs within the base contract. Further, the frontend contracts simply import the requisite methods and expose them with the `view` and `external` decorators.

2022-01-08 00:03 UTC, martriay requested changes
Almost there, suggestions below :)

2022-01-08 01:03 UTC, andrew-fleming commented on contracts/token/ERC20_base.cairo
> +func ERC20_name_{
Hmm I considered exporting the storage variables. I chose exportable setter methods for consistency, so I'm leaning that way—easy change if you think accessing the storage vars directly is the way to go here

2022-01-08 01:03 UTC, andrew-fleming commented on contracts/token/ERC20_base.cairo
> +    #ERC20_approve(caller, spender, new_allowance)
Ahhh! It should not!

2022-01-08 03:45 UTC, martriay commented on contracts/token/ERC20_base.cairo
> +func ERC20_name_{
I think it's an unneeded indirection, let's use storage vars.

2022-01-12 04:35 UTC, martriay approved these changes

2022-01-12 04:35 UTC, merged

2022-01-12 04:35 UTC, martriay commented
Thanks!