Add access control to ERC721.setTokenURI
OpenZeppelin/cairo-contracts pull request #159
Opened 2022-01-22 03:39 UTC by andrew-fleming

Fixes #156.

2022-01-22 04:09 UTC, martriay requested changes
Looking good :)
I think we should also add a test.

2022-01-24 15:25 UTC, frangio commented
Sorry but the resulting contract feels strange to me. It's like a weird subset of ERC721_Mintable.

What use case is ERC721.cairo meant for? Since it's not mintable, it looks like by itself it doesn't do anything so it would either have to be used as a template or extended via `import` and adding new external functions. It may make more sense to remove `setTokenURI`.

2022-01-24 17:18 UTC, andrew-fleming commented
That's fair. I suppose we can also remove the Ownable imports as well since they're only used for `setTokenURI`.

2022-01-25 08:34 UTC, martriay approved these changes

2022-01-25 08:34 UTC, merged