Add overflow checks with new library
OpenZeppelin/cairo-contracts pull request #160
Opened 2022-01-22 21:18 UTC by andrew-fleming

## Summary

This PR resolves #155 by including `uint256_check` on all uint256 arguments in `ERC721_base` and checks for overflows on all uint256 arithmetic operations. Further, this PR proposes that a new library `Uint256_Checked_base` should be used for uint256 arithmetic operations (recommended by @frangio). The `Uint256_Checked_base` methods perform the operation between two uint256 values and thereafter checks for overflows. 

This PR also includes new testing functions for adding and subtracting uint256 values which are necessary because they:
- separate integers into a tuple of two 128-bit values. This matches up with how uint256 values are structured in Cairo
- increase the readability of tests
- alleviate the strain of writing uint256 arithmetic e.g. 
```
a = (123, 4)
b = (567, 8)

# PROBLEM
sum = [
    a[0] + b[0],
    a[1] + b[1]
]

# PROPOSED SOLUTION
sum = uint_add(a, b)
```

## Future
If this PR is accepted, we should consider:
- updating all contracts with `Uint256_Checked` methods
- perhaps renaming the directory where `Uint256_Checked` resides (`contracts/utils/`) especially since `utils.py` documentation is a priority

2022-01-25 13:34 UTC, frangio commented
I don't see this as a contract or contract "base", just a library of internal functions, so I think we can drop the capital letters as well as the `_base` suffix (not used in the new naming convention anyway, right), and name the module `uint256_checked`.

2022-01-25 13:35 UTC, frangio commented
@martriay Is this PR on hold to check if StarkWare would rather offer these functions built into cairo?

2022-01-25 17:09 UTC, martriay commented
> @martriay Is this PR on hold to check if StarkWare would rather offer these functions built into cairo?

No, this has to be merged asap so we can release it

2022-01-27 01:06 UTC, martriay requested changes
Great addition. Left some comments.

2022-01-27 01:06 UTC, martriay commented on contracts/utils/uint256_checked_test.cairo
> +%lang starknet
not sure if we want test contracts to be in here or `tests/`. otherwise they will be part of the exposed library.

2022-01-27 01:06 UTC, martriay commented on contracts/utils/uint256_checked.cairo
> +    } (a: Uint256, b: Uint256) -> (c: Uint256):
should we also validate `a` and `b` are proper `Uint`s? i.e. use `uint256_check`

2022-01-27 01:06 UTC, martriay commented on tests/test_uint256_checked.py
> +    c = add_uint(a, b)
don't we have an `uint()` interface already in `utils.py`? we should be consistent so whenever we change anything in it, it propagates across the codebase

2022-01-27 01:06 UTC, martriay commented on tests/test_uint256_checked.py
> +    assert execution_info.result == (c,)
maybe we can have an `equal` case for `uint256_checked_sub_lt` too

2022-01-27 17:15 UTC, frangio commented on contracts/utils/uint256_checked.cairo
> +    return (c)
`b <= a` feels more direct to me. (I.e. better)

2022-01-28 05:23 UTC, martriay approved these changes
Looks good to me :)

Please resolve conflicts and merge

2022-01-28 05:28 UTC, andrew-fleming commented
Thank you, sir! Will do

2022-01-28 07:40 UTC, merged