Fix event param in erc20 and erc721
OpenZeppelin/cairo-contracts pull request #226
Opened 2022-03-19 19:37 UTC by andrew-fleming

Resolves #219.

2022-03-21 04:45 UTC, martriay approved these changes

2022-03-21 04:46 UTC, martriay requested changes
I think we should propagate this across the codebase not just on the events.

2022-03-22 06:47 UTC, eddiexbank approved these changes

2022-03-22 23:14 UTC, martriay approved these changes

2022-03-22 23:14 UTC, merged