Update ownable check to validate zero address
OpenZeppelin/cairo-contracts pull request #398
Opened 2022-07-13 16:11 UTC by JulissaDantes

Fixes #374  

Includes: 
- Extra check for caller to not be zero address when using `assert_only_owner`.
- Test case to revert if protected function gets called after the renounce ownership. 

#### PR Checklist

- [x] Tests
- [x] Documentation
- [ ] Changelog entry

2022-07-13 23:32 UTC, andrew-fleming reviewed
Looks good to me! We should probably document this check as well—maybe a small note in the `assert_only_owner` description?

2022-07-14 11:42 UTC, martriay requested changes
Added some comments on top of Andrew's.

2022-07-14 11:42 UTC, martriay commented on tests/access/test_Ownable.py
> +
I don't think this belongs to this test. This assert is not testing the `renounceOwnership` function, but `assert_only_owner`. Put differently if this assert fails, one should not think there's a problem with `renounceOwnership`.

2022-07-18 03:14 UTC, andrew-fleming reviewed
Great improvements! I left a couple small suggestions and a question :)

2022-07-18 03:14 UTC, andrew-fleming commented on tests/access/test_Ownable.py
> +        ownable.protected_function().call(),
This should be `.invoke()`, no?

2022-07-18 14:20 UTC, martriay approved these changes
Looks good!

2022-07-18 14:20 UTC, martriay commented on tests/access/test_Ownable.py
> +    # Protected function cannot be called from zero address
```suggestion
    # Protected function should not be called from zero address
```

2022-07-19 19:44 UTC, merged